<a href="https://colab.research.google.com/github/Angepira/AngePira.github.io/blob/main/Clase_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recuperar y procesar los datos almacenados

En este notebook vamos a aprender a:
- Explorar los dataframes 
- Leer y guardar archivos con ayuda de las liberías pandas y numpy

## Leyendo y guardando archivos

### Numpy


**Leer archivos CSV**

In [ ]:
#Importamos librerías
from numpy import genfromtxt
import numpy as np 

In [ ]:
#Cargamos el archivo desde link
#El archivo se llama "demo.csv"
url = "https://drive.google.com/file/d/1ODn7yvHW6QT-STxTMNbG7Agyt2gN2VJo/view?usp=sharing"
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]

In [ ]:
#Abrimos el archivo con numpy y lo imprimimos
product_data = genfromtxt(path, delimiter=',')
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [ ]:
#Si no lo imprimmos lo muestra como un array de numpy
product_data

array([[14., 32., 33.],
       [24., 45., 26.],
       [27., 38., 39.]])

¿Puedo leer archivos de csv que tenga strings con numpy?

**Escribir archivos CSV**


In [ ]:
#Creo un array
sample_array = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Guardamos el array como csv
np.savetxt("my_first_demo_numpy.csv", sample_array, delimiter=",") 

### Pandas


#### CSV

**Leyendo archivos CSV**

In [ ]:
#Tomamos el mismo path de arriba
#El archivo se llama "demo.csv"
path

'https://drive.google.com/uc?export=download&id=1ODn7yvHW6QT-STxTMNbG7Agyt2gN2VJo'

In [ ]:
#importamos la librería
import pandas as pd 

In [ ]:
sample_df = pd.read_csv(path)
sample_df

14  32  33
0  24  45  26
1  27  38  39

In [ ]:
sample_df = pd.read_csv(path, sep=',',header=None)
sample_df.head() 

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

**Escribiendo archivos CSV**


In [ ]:
sample_df.to_csv('demo_sample_df_pandas.csv') 

#### Excel


Leyendo datos

In [ ]:
#Cargamos el archivo desde link
#El archivo se llama 'employee.xlsx'
url2 = "https://docs.google.com/spreadsheets/d/1wluZRQBbRPaX5u1omZbcaUizMjB6TC5T/edit?usp=share_link&ouid=102253785812570814884&rtpof=true&sd=true"
path2 = 'https://drive.google.com/uc?export=download&id='+url2.split('/')[-2]

In [ ]:
pd.read_excel(path2)

name   age   income gender  department grade
0    Allen Smith  45.0      NaN    NaN  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3
6   James Authur  54.0      NaN      F  Operations    G3
7     Josh Wills  54.0  52000.0      F     Finance    G3
8       Leo Duck  23.0  98000.0      M       Sales    G4

In [ ]:
emp_df = pd.read_excel(path2, sheet_name='performance')
emp_df

name  performance_score
0    Allen Smith                723
1        S Kumar                520
2    Jack Morgan                674
3      Ying Chin                556
4  Dheeraj Patel                711
5  Satyam Sharma                649
6   James Authur                 53
7     Josh Wills                901
8       Leo Duck                709

**Escribiendo datos**


In [ ]:
with pd.ExcelWriter('new_employee_details.xlsx') as writer:
  emp_df.to_excel(writer, sheet_name='employee')
  emp_df.to_excel(writer, sheet_name='performance') 

#### JSON

**Leyendo datos**

In [ ]:
#Cargamos el archivo desde link
#El archivo se llama 'employee.json'
url3 = "https://drive.google.com/file/d/16bEvPX-QmHqNsuz1zCibWaeRYsHn2-6N/view?usp=sharing"
path3 = 'https://drive.google.com/uc?export=download&id='+url3.split('/')[-2]

In [ ]:
df = pd.read_json(path3)
df

name   age   income gender  department grade
0    Allen Smith  45.0      NaN   None  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2
5  Satyam Sharma   NaN  62000.0   None       Sales    G3
6   James Authur  54.0      NaN      F  Operations    G3
7     Josh Wills  54.0  52000.0      F     Finance    G3
8       Leo Duck  23.0  98000.0      M       Sales    G4

**Escribiendo datos**

In [ ]:
df.to_json('employee_demo.json', orient="columns") 

#### HTML


**Leyendo datos**

In [ ]:
table_url = 'https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America'
table_url

'https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America'

In [ ]:
df_list = pd.read_html(table_url)
df_list[:1]

[    Flag  Map  English short, formal names, and ISO [1][2][3][4]  \
 0    NaN  NaN                       Antigua and Barbuda[n 1] ATG   
 1    NaN  NaN  Bahamas, The[n 1] Commonwealth of The Bahamas BHS   
 2    NaN  NaN                                  Barbados[n 1] BRB   
 3    NaN  NaN                               Belize[n 1][n 2] BLZ   
 4    NaN  NaN                                    Canada[n 3] CAN   
 5    NaN  NaN         Costa Rica[n 2] Republic of Costa Rica CRI   
 6    NaN  NaN                          Cuba Republic of Cuba CUB   
 7    NaN  NaN         Dominica[n 1] Commonwealth of Dominica DMA   
 8    NaN  NaN                        Dominican Republic[n 2] DOM   
 9    NaN  NaN       El Salvador[n 2] Republic of El Salvador SLV   
 10   NaN  NaN                                   Grenada[n 1] GRD   
 11   NaN  NaN           Guatemala[n 2] Republic of Guatemala GTM   
 12   NaN  NaN                   Haiti[n 1] Republic of Haiti HTI   
 13   NaN  NaN             Hondura

In [ ]:
len(df_list)

9

In [ ]:
for i in df_list:
  print(i.shape)
  print(i.head(1))

(23, 8)
   Flag  Map English short, formal names, and ISO [1][2][3][4]  \
0   NaN  NaN                      Antigua and Barbuda[n 1] ATG   

  Domestic short and formal name(s) [1][2] Capital [3][5][6]  \
0             English: Antigua and Barbuda        St. John's   

   Population 2021 [7][8]               Area [9]           Currency [3]  
0                   93219  442.6 km2 (171 sq mi)  East Caribbean dollar  
(9, 9)
   Flag English short, formal names, and ISO Domestic short name(s)  \
0   NaN                         Anguilla AIA      English: Anguilla   

      Capital  Population 2021                Area               Currency  \
0  The Valley            15753  102 km2 (39 sq mi)  East Caribbean dollar   

  Sovereign state                Legal status  
0  United Kingdom  British Overseas Territory  
(16, 9)
   Flag English short, formal names, and ISO Domestic short name(s)  \
0   NaN           Aruba Country of Aruba ABW           Dutch: Aruba   

      Capital  Population 2021

In [ ]:
df_list[1].to_html('country2.html')

In [ ]:
df_list[1].to_csv('country.csv')